import type { LibrarySnapshot } from "./types";

export const demoSnapshot: LibrarySnapshot = {
  papers: [
    {
      id: "paper-retrieval",
      title: "Adaptive Retrieval for Long-Context Scientific Assistants",
      abstract:
        "We introduce a retrieval controller that learns when and where to search across long scientific documents, improving grounded question answering while reducing unnecessary context.",
      year: 2026,
      paperType: "conference",
      volume: null,
      issue: null,
      pages: null,
      category: "cs.IR",
      doi: "10.5555/pa.2026.001",
      arxivId: null,
      preprintId: null,
      semanticScholarId: "s2-retrieval",
      url: "https://arxiv.org/abs/2602.01472",
      pdfUrl: "https://arxiv.org/pdf/2602.01472",
      pdfViewUrl: "https://arxiv.org/pdf/2602.01472",
      localPath: null,
      htmlSnapshotPath: null,
      htmlUrl: null,
      summary: "A retrieval controller learns when and where to search long scientific documents, improving grounded question answering while reducing unnecessary context use.",
      notes: "Compare the ablation on retrieval depth with our literature graph baseline.",
      readingStatus: "reading",
      favorite: true,
      venueId: "venue-neurips",
      venueName: "Conference on Neural Information Processing Systems",
      venueAcronym: "NeurIPS",
      addedAt: "2026-07-12T14:32:00Z",
      updatedAt: "2026-07-12T14:32:00Z",
      authors: [
        {
          id: "author-amina",
          displayName: "Amina Rahman",
          orcid: "0000-0002-3141-5926",
          order: 0,
          corresponding: true,
        },
        {
          id: "author-theo",
          displayName: "Theo Martins",
          orcid: "0000-0001-7462-9012",
          order: 1,
          corresponding: false,
        },
      ],
      collections: [{ id: "collection-active", name: "Active review", color: "amber" }],
    },
    {
      id: "paper-sensemaking",
      title: "Interfaces for Human–AI Literature Sensemaking",
      abstract:
        "A mixed-methods study of interface patterns that help researchers synthesize unfamiliar literatures with generative AI while preserving provenance and agency.",
      year: 2025,
      paperType: "conference",
      volume: null,
      issue: null,
      pages: "1–18",
      category: "cs.HC",
      doi: "10.1145/pa.2025.014",
      arxivId: null,
      preprintId: null,
      semanticScholarId: "s2-sensemaking",
      url: "https://dl.acm.org/doi/10.1145/pa.2025.014",
      pdfUrl: null,
      pdfViewUrl: null,
      localPath: null,
      htmlSnapshotPath: null,
      htmlUrl: null,
      summary: "A mixed-methods study identifies interface patterns that preserve researcher agency and provenance when generative AI supports literature synthesis.",
      notes: "Useful taxonomy for the related-work workspace.",
      readingStatus: "complete",
      favorite: true,
      venueId: "venue-chi",
      venueName: "ACM Conference on Human Factors in Computing Systems",
      venueAcronym: "CHI",
      addedAt: "2026-07-09T09:15:00Z",
      updatedAt: "2026-07-09T09:15:00Z",
      authors: [
        {
          id: "author-lena",
          displayName: "Lena Ortiz",
          orcid: "0000-0002-5579-2401",
          order: 0,
          corresponding: true,
        },
        {
          id: "author-amina",
          displayName: "Amina Rahman",
          orcid: "0000-0002-3141-5926",
          order: 1,
          corresponding: false,
        },
      ],
      collections: [
        { id: "collection-active", name: "Active review", color: "amber" },
        { id: "collection-interface", name: "Interface patterns", color: "violet" },
      ],
    },
    {
      id: "paper-agents",
      title: "Reliable Tool Use in Autonomous Research Agents",
      abstract:
        "We study failure recovery, verification, and cost-aware planning in autonomous agents that operate over scholarly search and document tools.",
      year: 2026,
      paperType: "preprint",
      volume: null,
      issue: null,
      pages: null,
      category: "cs.AI",
      doi: null,
      arxivId: "arXiv:2605.09104",
      preprintId: "arXiv:2605.09104",
      semanticScholarId: "s2-agents",
      url: "https://arxiv.org/abs/2605.09104",
      pdfUrl: "https://arxiv.org/pdf/2605.09104",
      pdfViewUrl: "https://arxiv.org/pdf/2605.09104",
      localPath: null,
      htmlSnapshotPath: null,
      htmlUrl: null,
      summary: "The paper studies failure recovery, verification, and cost-aware planning in agents operating over scholarly search and document tools.",
      notes: "Read sections 4 and 6 next.",
      readingStatus: "inbox",
      favorite: false,
      venueId: "venue-arxiv",
      venueName: "arXiv",
      venueAcronym: "arXiv",
      addedAt: "2026-07-07T16:48:00Z",
      updatedAt: "2026-07-07T16:48:00Z",
      authors: [
        {
          id: "author-sam",
          displayName: "Samir Patel",
          orcid: "0000-0001-6034-8752",
          order: 0,
          corresponding: true,
        },
        {
          id: "author-yuki",
          displayName: "Yuki Tanaka",
          orcid: "0000-0003-8420-1187",
          order: 1,
          corresponding: false,
        },
      ],
      collections: [{ id: "collection-agents", name: "Research agents", color: "green" }],
    },
    {
      id: "paper-memory",
      title: "Memory Architectures for Continual Scientific Discovery",
      abstract:
        "A perspective on episodic, semantic, and procedural memory for systems that support multi-month research programs.",
      year: 2025,
      paperType: "journal",
      volume: "7",
      issue: "4",
      pages: "312–326",
      category: "cs.AI",
      doi: "10.1038/pa.2025.812",
      arxivId: null,
      preprintId: null,
      semanticScholarId: "s2-memory",
      url: "https://www.nature.com/articles/pa-2025-812",
      pdfUrl: null,
      pdfViewUrl: null,
      localPath: null,
      htmlSnapshotPath: null,
      htmlUrl: null,
      summary: "A perspective on episodic, semantic, and procedural memory for systems supporting multi-month research programs.",
      notes: "Connect to the lab notebook export design.",
      readingStatus: "reading",
      favorite: false,
      venueId: "venue-nature",
      venueName: "Nature Machine Intelligence",
      venueAcronym: "NMI",
      addedAt: "2026-07-03T11:20:00Z",
      updatedAt: "2026-07-03T11:20:00Z",
      authors: [
        {
          id: "author-yuki",
          displayName: "Yuki Tanaka",
          orcid: "0000-0003-8420-1187",
          order: 0,
          corresponding: true,
        },
        {
          id: "author-sam",
          displayName: "Samir Patel",
          orcid: "0000-0001-6034-8752",
          order: 1,
          corresponding: false,
        },
      ],
      collections: [],
    },
    {
      id: "paper-graphs",
      title: "Scholarly Graphs as Navigable Research Context",
      abstract:
        "This work combines citation graphs, author entities, and venue priors into an interactive substrate for exploratory literature review.",
      year: 2024,
      paperType: "preprint",
      volume: null,
      issue: null,
      pages: null,
      category: "cs.DL",
      doi: null,
      arxivId: "arXiv:2409.11880",
      preprintId: "arXiv:2409.11880",
      semanticScholarId: "s2-graphs",
      url: "https://arxiv.org/abs/2409.11880",
      pdfUrl: "https://arxiv.org/pdf/2409.11880",
      pdfViewUrl: "https://arxiv.org/pdf/2409.11880",
      localPath: null,
      htmlSnapshotPath: null,
      htmlUrl: null,
      summary: "Citation graphs, author entities, and venue priors are combined into an interactive substrate for exploratory literature review.",
      notes: "Potential foundation for author and venue views.",
      readingStatus: "complete",
      favorite: false,
      venueId: "venue-arxiv",
      venueName: "arXiv",
      venueAcronym: "arXiv",
      addedAt: "2026-06-27T13:05:00Z",
      updatedAt: "2026-06-27T13:05:00Z",
      authors: [
        {
          id: "author-theo",
          displayName: "Theo Martins",
          orcid: "0000-0001-7462-9012",
          order: 0,
          corresponding: true,
        },
        {
          id: "author-lena",
          displayName: "Lena Ortiz",
          orcid: "0000-0002-5579-2401",
          order: 1,
          corresponding: false,
        },
      ],
      collections: [{ id: "collection-interface", name: "Interface patterns", color: "violet" }],
    },
  ],
  authors: [
    { id: "author-amina", displayName: "Amina Rahman", givenName: "Amina", familyName: "Rahman", orcid: "0000-0002-3141-5926", semanticScholarId: "s2-amina", notes: null, paperCount: 2, latestYear: 2026 },
    { id: "author-lena", displayName: "Lena Ortiz", givenName: "Lena", familyName: "Ortiz", orcid: "0000-0002-5579-2401", semanticScholarId: "s2-lena", notes: null, paperCount: 2, latestYear: 2025 },
    { id: "author-sam", displayName: "Samir Patel", givenName: "Samir", familyName: "Patel", orcid: "0000-0001-6034-8752", semanticScholarId: "s2-samir", notes: null, paperCount: 2, latestYear: 2026 },
    { id: "author-theo", displayName: "Theo Martins", givenName: "Theo", familyName: "Martins", orcid: "0000-0001-7462-9012", semanticScholarId: "s2-theo", notes: null, paperCount: 2, latestYear: 2026 },
    { id: "author-yuki", displayName: "Yuki Tanaka", givenName: "Yuki", familyName: "Tanaka", orcid: "0000-0003-8420-1187", semanticScholarId: "s2-yuki", notes: null, paperCount: 2, latestYear: 2026 },
  ],
  venues: [
    { id: "venue-neurips", name: "Conference on Neural Information Processing Systems", acronym: "NeurIPS", type: "conference", publisher: "NeurIPS Foundation", url: "https://neurips.cc", notes: null, paperCount: 1, latestYear: 2026 },
    { id: "venue-chi", name: "ACM Conference on Human Factors in Computing Systems", acronym: "CHI", type: "conference", publisher: "ACM", url: "https://chi.acm.org", notes: null, paperCount: 1, latestYear: 2025 },
    { id: "venue-nature", name: "Nature Machine Intelligence", acronym: "NMI", type: "journal", publisher: "Springer Nature", url: "https://www.nature.com/natmachintell", notes: null, paperCount: 1, latestYear: 2025 },
    { id: "venue-arxiv", name: "arXiv", acronym: "arXiv", type: "preprint", publisher: "Cornell Tech", url: "https://arxiv.org", notes: null, paperCount: 2, latestYear: 2026 },
  ],
  collections: [
    { id: "collection-active", name: "Active review", color: "amber", paperCount: 2 },
    { id: "collection-agents", name: "Research agents", color: "green", paperCount: 1 },
    { id: "collection-interface", name: "Interface patterns", color: "violet", paperCount: 2 },
  ],
  stats: { papers: 5, authors: 5, venues: 4, unread: 1, active: 2, recent: 2 },
};
