import { chmodSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const libDir = mkdtempSync(join(tmpdir(), "wfdrv-"));
process.env.STACKS_LIBRARY_DIR = libDir;
const stub = join(libDir, "c.sh");
writeFileSync(stub, `#!/bin/sh\nsleep 0.4\nprintf '%s\\n' '{"type":"result","is_error":false,"result":"OK"}'\n`);
chmodSync(stub, 0o755);
process.env.STACKS_CLAUDE_BIN = stub;
globalThis.fetch = (async () => { throw new Error("no network"); }) as any;
const { runWorkflow } = await import("/Users/SXKDZ/Documents/Coding/Repository/PaperAssistant/app/lib/workflow-runtime.ts");
const { ensureDatabase } = await import("/Users/SXKDZ/Documents/Coding/Repository/PaperAssistant/db/bootstrap.ts");
const { feedSnippets } = await import("/Users/SXKDZ/Documents/Coding/Repository/PaperAssistant/db/schema.ts");
const { eq } = await import("drizzle-orm");
const db = await ensureDatabase();
const now = new Date().toISOString();
db.insert(feedSnippets).values({ id: "mid", title: "t", instruction: "i", status: "queued", sessionId: "", createdAt: now, updatedAt: now }).run();
let outcome = "resolved";
const p = runWorkflow({ snippetId: "mid", script: `export const meta = { name: "n", description: "d" };\nawait agent("go");\nlog("after-delete");` }).catch((e) => { outcome = "rejected:" + (e as Error).message; });
setTimeout(() => db.delete(feedSnippets).where(eq(feedSnippets.id, "mid")).run(), 150);
await p;
await new Promise((r) => setTimeout(r, 600));
console.log("OUTCOME " + outcome);
